### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by ryansoeder** [ryansoeder/cactusflower#2]
## TODO
*Tasks to improve web site*

* [ ] get better photos
* [x] add parallax scrolling image under header
* [x] beter font for footer links
* [x] remove box shadow a:hover and use font-color instead
* [x] increase footer size
